services:
  ft_transcendence:
    container_name: ft_transcendence
    build: .
    image: ft_transcendence
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
      - ./.env:/app/.env
    environment:
      - JWT_SECRET=your_jwt_secret
      - COOKIE_SECRET=your_cookie_secret
      - REFRESH_TOKEN_SECRET=your_refresh_token_secret
    tty: true
    stdin_open: true
