services:
  ft_transcendence:
    container_name: ft_transcendence
    build: .
    image: ft_transcendence
    ports:
      - "3000:3000"
      - "4040:4040"
    volumes:
      - ./src:/app
    env_file:
      - ./.env
    tty: true
    stdin_open: true
