services:
  ft_transcendence:
    container_name: ft_transcendence
    build: .
    image: ft_transcendence
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
      - ./.env:/app/.env
    tty: true
    stdin_open: true
