export type ThemeName = 'stars' | 'mechazilla' | 'starship' | 'default';
export declare function themedBtn(theme: ThemeName): string;
export declare function themedCard(theme: ThemeName): string;
export declare function themedInput(theme: ThemeName): string;
export declare function themedLabel(theme: ThemeName): string;
export declare function themedStat(theme: ThemeName): string;
export declare function themedTitle(theme: ThemeName): string;
export declare function themedSubtitle(theme: ThemeName): string;
export declare function themedToggle(theme: ThemeName): string;
export declare function themedToggleLabel(theme: ThemeName): string;
export declare function getThemeBackground(theme: ThemeName): string;
